CREATE TABLE "user" (
                        "id" UUID NOT NULL UNIQUE,
                        "first_name" VARCHAR(255) NOT NULL,
                        "last_name" VARCHAR(255) NOT NULL,
                        "birth_date" DATE NOT NULL,
                        "email" VARCHAR(255) NOT NULL UNIQUE,
                        "password" VARCHAR(255) NOT NULL,
                        "created_at" TIMESTAMP NOT NULL,
                        "verified" BOOLEAN NOT NULL,
                        "role_id" INTEGER NOT NULL,
                        PRIMARY KEY("id")
);

CREATE TABLE "event" (
                         "id" BIGSERIAL NOT NULL UNIQUE,
                         "name" VARCHAR(255) NOT NULL,
                         "date" DATE NOT NULL,
                         "track_id" BIGINT NOT NULL,
                         PRIMARY KEY("id")
);

CREATE TABLE "event_registration" (
                                      "id" UUID NOT NULL UNIQUE,
                                      "event_id" BIGINT NOT NULL,
                                      "user_id" UUID NOT NULL,
                                      "vehicle_id" BIGINT NOT NULL,
                                      "category_id" INTEGER NOT NULL,
                                      "racing_number" INTEGER NOT NULL,
                                      "created_at" TIMESTAMP NOT NULL,
                                      PRIMARY KEY("id"),
                                      CONSTRAINT event_registration_unique_racing_number UNIQUE (event_id, racing_number),
                                      CONSTRAINT event_registration_unique_user UNIQUE (event_id, user_id)
);

CREATE TABLE "session" (
                           "id" BIGSERIAL NOT NULL UNIQUE,
                           "event_id" BIGINT NOT NULL,
                           "type_id" INTEGER NOT NULL,
                           "ordinal_number" INTEGER NOT NULL,
                           "name" VARCHAR(255) NOT NULL,
                           "laps_limit" INTEGER NOT NULL,
                           PRIMARY KEY("id", "event_id", "name")
);

CREATE TABLE "lap" (
                       "id" BIGSERIAL NOT NULL UNIQUE,
                       "session_id" BIGINT NOT NULL,
                       "racing_number" INTEGER NOT NULL,
                       "lap_time" BIGINT NOT NULL,
                       PRIMARY KEY("id")
);

CREATE TABLE "track" (
                         "id" BIGSERIAL NOT NULL UNIQUE,
                         "name" VARCHAR(255) NOT NULL UNIQUE,
                         PRIMARY KEY("id")
);

CREATE TABLE "vehicle" (
                           "id" BIGSERIAL NOT NULL UNIQUE,
                           "user_id" UUID NOT NULL,
                           "make" VARCHAR(255) NOT NULL,
                           "model" VARCHAR(255) NOT NULL,
                           "year" INTEGER NOT NULL,
                           "deleted" BOOLEAN NOT NULL,
                           PRIMARY KEY("id")
);

CREATE TABLE "session_type" (
                                "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                "name" VARCHAR(255) NOT NULL UNIQUE,
                                PRIMARY KEY("id")
);COMMENT ON COLUMN session_type.name IS 'Type of event session';


CREATE TABLE "classification_category" (
                                           "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                           "name" VARCHAR(255) NOT NULL,
                                           "max_power" INTEGER NOT NULL,
                                           "wheel_drive_type" VARCHAR(255) NOT NULL,
                                           PRIMARY KEY("id")
);

CREATE TABLE "user_token" (
                              "id" UUID NOT NULL UNIQUE,
                              "refresh_token" TEXT NOT NULL,
                              "user_id" UUID NOT NULL,
                              PRIMARY KEY("id")
);

CREATE TABLE "events_categories" (
                                     "event_id" BIGINT NOT NULL,
                                     "category_id" BIGINT NOT NULL,
                                     PRIMARY KEY("event_id", "category_id")
);

CREATE TABLE "role" (
                        "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                        "name" VARCHAR(255) NOT NULL UNIQUE,
                        PRIMARY KEY("id")
);

CREATE TABLE "scope" (
                         "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                         "code" VARCHAR(255) NOT NULL UNIQUE,
                         PRIMARY KEY("id")
);

CREATE TABLE "roles_scopes" (
                                "role_id" INTEGER NOT NULL,
                                "scope_id" INTEGER NOT NULL,
                                PRIMARY KEY("role_id", "scope_id")
);

ALTER TABLE "event"
    ADD FOREIGN KEY("track_id") REFERENCES "track"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "event_registration"
    ADD FOREIGN KEY("event_id") REFERENCES "event"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "lap"
    ADD FOREIGN KEY("session_id") REFERENCES "session"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "vehicle"
    ADD FOREIGN KEY("user_id") REFERENCES "user"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "event_registration"
    ADD FOREIGN KEY("user_id") REFERENCES "user"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "event_registration"
    ADD FOREIGN KEY("vehicle_id") REFERENCES "vehicle"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "session"
    ADD FOREIGN KEY("event_id") REFERENCES "event"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "session"
    ADD FOREIGN KEY("type_id") REFERENCES "session_type"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "user_token"
    ADD FOREIGN KEY("user_id") REFERENCES "user"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "events_categories"
    ADD FOREIGN KEY("event_id") REFERENCES "event"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "events_categories"
    ADD FOREIGN KEY("category_id") REFERENCES "classification_category"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "event_registration"
    ADD FOREIGN KEY("category_id") REFERENCES "classification_category"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "user"
    ADD FOREIGN KEY("role_id") REFERENCES "role"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "roles_scopes"
    ADD FOREIGN KEY("role_id") REFERENCES "role"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "roles_scopes"
    ADD FOREIGN KEY("scope_id") REFERENCES "scope"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;




INSERT INTO "scope" (code) VALUES('CREATE_EVENTS');
INSERT INTO "scope" (code) VALUES('CREATE_SESSIONS');
INSERT INTO "scope" (code) VALUES('READ_REGISTRATIONS');
INSERT INTO "scope" (code) VALUES('READ_ALL_LAPS');
INSERT INTO "scope" (code) VALUES('APPLY_ROLES');
INSERT INTO "scope" (code) VALUES('UPLOAD_LAPS');
INSERT INTO "scope" (code) VALUES('CREATE_TRACKS');
INSERT INTO "scope" (code) VALUES('CREATE_REGISTRATIONS');
INSERT INTO "scope" (code) VALUES('READ_USER_DATA');
INSERT INTO "scope" (code) VALUES('WRITE_USER_DATA');


INSERT INTO "role" ("name") VALUES('USER');
INSERT INTO "role" ("name") VALUES('STUFF');
INSERT INTO "role" ("name") VALUES('ADMIN');


INSERT INTO roles_scopes (role_id, scope_id) VALUES(3, 1);
INSERT INTO roles_scopes (role_id, scope_id) VALUES(3, 2);
INSERT INTO roles_scopes (role_id, scope_id) VALUES(3, 3);
INSERT INTO roles_scopes (role_id, scope_id) VALUES(3, 4);
INSERT INTO roles_scopes (role_id, scope_id) VALUES(3, 5);
INSERT INTO roles_scopes (role_id, scope_id) VALUES(3, 6);
INSERT INTO roles_scopes (role_id, scope_id) VALUES(3, 7);
INSERT INTO roles_scopes (role_id, scope_id) VALUES(3, 8);
INSERT INTO roles_scopes (role_id, scope_id) VALUES(3, 9);
INSERT INTO roles_scopes (role_id, scope_id) VALUES(3, 10);

INSERT INTO roles_scopes (role_id, scope_id) VALUES(2, 2);
INSERT INTO roles_scopes (role_id, scope_id) VALUES(2, 3);
INSERT INTO roles_scopes (role_id, scope_id) VALUES(2, 4);
INSERT INTO roles_scopes (role_id, scope_id) VALUES(2, 6);
INSERT INTO roles_scopes (role_id, scope_id) VALUES(2, 8);
INSERT INTO roles_scopes (role_id, scope_id) VALUES(2, 9);
INSERT INTO roles_scopes (role_id, scope_id) VALUES(2, 10);

INSERT INTO roles_scopes (role_id, scope_id) VALUES(1, 3);


INSERT INTO classification_category ("name", max_power, wheel_drive_type) VALUES('STREET', 120, 'RWD');
INSERT INTO classification_category ("name", max_power, wheel_drive_type) VALUES('STREET', 120, 'FWD');
INSERT INTO classification_category ("name", max_power, wheel_drive_type) VALUES('STREET', 120, 'AWD');

INSERT INTO classification_category ("name", max_power, wheel_drive_type) VALUES('SPORT', 250, 'RWD');
INSERT INTO classification_category ("name", max_power, wheel_drive_type) VALUES('SPORT', 250, 'FWD');
INSERT INTO classification_category ("name", max_power, wheel_drive_type) VALUES('SPORT', 250, 'AWD');

INSERT INTO classification_category ("name", max_power, wheel_drive_type) VALUES('EXTREME', 1000000, 'RWD');
INSERT INTO classification_category ("name", max_power, wheel_drive_type) VALUES('EXTREME', 1000000, 'FWD');
INSERT INTO classification_category ("name", max_power, wheel_drive_type) VALUES('EXTREME', 1000000, 'AWD');



INSERT INTO session_type ("name") VALUES('PRACTICE');
INSERT INTO session_type ("name") VALUES('COMPETITION');


INSERT INTO track ("name") VALUES('ADM Raceway');
INSERT INTO track ("name") VALUES('Moscow Raceway');
INSERT INTO track ("name") VALUES('NN Ring');