spring.application.name=time-attack-racing

spring.datasource.url={{ db_url }}
spring.datasource.username={{ db_username }}
spring.datasource.password={{ db_password }}

spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.security.oauth2.resourceserver.jwt.public-key-location={{ public_key_location}}
spring.security.oauth2.resourceserver.jwt.private-key-location={{ private_key_location}}

spring.jackson.property-naming-strategy=SNAKE_CASE

jwt.lifetime.minutes=5
jwt.lifetime.hours=12
