spring:
  shell:
    interactive:
      enabled: true
    context:
      close: true
  output:
    ansi:
      enabled: detect
  messages:
    baseName: languages/messages
    encoding: UTF-8
    # Не дает свалиться в системную локаль если не найден файл для переданной в MessageSource
    # Если false то будут браться сообщения из дефолтного файла, если true, то из файла соответствующего системной локали
    fallbackToSystemLocale: false
app:
  name: @project.name@
  version: @project.version@
test:
  rightAnswersCountToPass: 5
  locale: ru-RU
#  locale: en-US
  fileNameByLocaleTag:
    ru-RU: questions_ru.csv
    en-US: questions.csv